### ISSUE TITLE
Typo & suggestion for optimization

### ISSUE THREAD

**Issue by ihorskyi** [f/pq#1]
There is a typo in example:

``` javascript
  then(function () {
    return response.json()
  }).
```

Should be 

``` javascript
  then(function (response) {
    return response.json()
  }).
```

Another thing is that there will be a bit of an overhead for calling `.then(function)` every time there is no   async operations. Thus this would be great if could be done other way. For example:

``` javascript
var query = "(name, surname) of users of @json"
```

**ACTUAL:** 

``` javascript
fetch("/users").
  then(function (response) {
    return response.json()
  }).
  then(function (response) {
    return response.users
  }).
  then(function (response) {
    return response.map(function (object) { return {
      name: object.name,
      surname: object.surname
  }})
})

```

**EXPECTED:**

``` javascript
fetch("/users").
  then(function (response) {
    var json  = response.json()
    var users = response.users

    return users.map(function (object) { return {
      name: object.name,
      surname: object.surname
    }})
})
```

**Or optimized:**

``` javascript
fetch("/users").
  then(function (response) {
    return response.json().users.map(function (object) { return {
      name: object.name,
      surname: object.surname
    }})
})
```

**Comment by boneskull** [comment]
> Another thing is that there will be a bit of an overhead for calling .then(function) every time there is no async operations.

@ihorskyi It's not really "overhead"; it's a tradeoff.  With the "optimized" code you wrote, the thread will be blocking while processing the data.  You may want to avoid that as much as possible, depending on what you're up to.

FWIW, this:

```js
fetch("/users").
  then(function (response) {
    return response.json()
  }).
  then(function (response) {
    return response.users
  }).
  then(function (response) {
    return response.map(function (object) { return {
      name: object.name,
      surname: object.surname
  }})
})
```

becomes the following code, using [Bluebird](https://npmjs.com/package/bluebird):

```js
// untested
fetch('/users/').call('json').get('users').map(({name, surname}) => ({name, surname}))
```

It's unclear if the example in `README.md` is supposed to be real code, but it seems unnecessarily verbose.

@f I hope you will accept some constructive criticism.  

Some alternate ways of solving your problem may be:

- Try Bluebird
- Modify your endpoint to accept querystrings that can give you the data you need w/o client-side post-processing
- Explore something like GraphQL or Falcor

And my subjective opinions:  

- Overall, the syntax of this module isn't very human-readable.  It should immediately make sense, and it does not.  
- I'd avoid adding a module like `pq` to my package's dependencies, because of the overhead of learning a DSL--not just for me, but for other developers who would become confused and have to learn it as well.
- I'm unsure if `pq` really has much to do with Promises as stated.  What about concurrency?  Error handling?  What this really looks like is a way to process data structures.

**Comment by f** [comment]
@boneskull Thank you for your feedback which makes sense each.

Actually this is a part of a framework I build for my company and I open sourced it.

- I use bluebird, that's awesome but I'll explain why I didn't want to use it.
- Our back-end data is not able to change for the client since lots of clients (mobile, etc.) using them. It must be generic and I am not the one who writes that back-end :)
- I love GraphQL or Falcor, but these are also requires back-end which is not possible to me in my work.

Here's the story why I needed a library something like that:
At work, we are building clients for Oracle Micros systems and we have a generic REST gateway to connect them. I am a front-end developer and use same gateway again and again. So I decided to build a front-end framework which is very declarative.

This is an example how I write a simple hamburger list:
```html
<ul data-ql="(name, price) of @items of find({name: 'hamburger'}) of menus" data-ctrl="HamburgersList">
  {% $data.forEach(function (item) { %}
  <li> {{ item.name }} costs {{ item.price }} </li>
  {% }) %}
</ul>
```

In a pragmatic aspect of view, this become very handy. And as you can see `(name, price) of @items of find({name: 'hamburger'}) of menus` immediately makes sense. The `data-ql` part is doing a promised chain call.

That's the story of the **pq** :)

**pq** is *not* a replacement of Promises, but may be a completion to them. They allows you to create shortcuts. So concurrency is not my concern but error handling is. I need to figure how to handle `catch`es using QL :)

**Comment by f** [comment]
@ihorskyi @boneskull I updated the README file, please check :)
